//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class sulEntities : DbContext
{
    public sulEntities()
        : base("name=sulEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual ObjectResult<spTransaction_Result> spTransaction(Nullable<int> itemId, Nullable<int> invTypeId, Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, Nullable<int> storeId)
    {
        var itemIdParameter = itemId.HasValue ?
            new ObjectParameter("ItemId", itemId) :
            new ObjectParameter("ItemId", typeof(int));

        var invTypeIdParameter = invTypeId.HasValue ?
            new ObjectParameter("InvTypeId", invTypeId) :
            new ObjectParameter("InvTypeId", typeof(int));

        var dateFromParameter = dateFrom.HasValue ?
            new ObjectParameter("DateFrom", dateFrom) :
            new ObjectParameter("DateFrom", typeof(System.DateTime));

        var dateToParameter = dateTo.HasValue ?
            new ObjectParameter("DateTo", dateTo) :
            new ObjectParameter("DateTo", typeof(System.DateTime));

        var storeIdParameter = storeId.HasValue ?
            new ObjectParameter("StoreId", storeId) :
            new ObjectParameter("StoreId", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spTransaction_Result>("spTransaction", itemIdParameter, invTypeIdParameter, dateFromParameter, dateToParameter, storeIdParameter);
    }
}
