//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class spTransaction_Result
{
    public string catProduct { get; set; }
    public Nullable<double> QtyOpenBlanace { get; set; }
    public Nullable<double> PriceOpenBlanace { get; set; }
    public Nullable<System.DateTime> CreatedOn { get; set; }
    public Nullable<double> InvId { get; set; }
    public Nullable<int> InvType { get; set; }
    public string InvTypeNameL1 { get; set; }
    public Nullable<double> ItemQty { get; set; }
    public string UnitName { get; set; }
    public Nullable<double> Total { get; set; }
    public double QtyIn { get; set; }
    public double PriceIn { get; set; }
    public double QtyOut { get; set; }
    public double PriceOut { get; set; }
    public string InvItemNameL1 { get; set; }
    public Nullable<int> InvItemId { get; set; }
    public double ItemLastQty { get; set; }
    public double ItemNewQty { get; set; }
    public double ItemLastCost { get; set; }
    public double ItemNewCost { get; set; }
    public double Price { get; set; }
    public Nullable<int> Type { get; set; }
}
