//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSERP.Views.Shared.appResource.loginResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class loginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal loginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appSERP.Views.Shared.appResource.loginResource.loginResource", typeof(loginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحقق من الكود.
        /// </summary>
        public static string btnCheckCode {
            get {
                return ResourceManager.GetString("btnCheckCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال الكود.
        /// </summary>
        public static string btnSendCode {
            get {
                return ResourceManager.GetString("btnSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت إسم المستخدم أو كلمة المرور.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        public static string gCode {
            get {
                return ResourceManager.GetString("gCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكترونى.
        /// </summary>
        public static string gEmail {
            get {
                return ResourceManager.GetString("gEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز التحقق.
        /// </summary>
        public static string lblCaptcha {
            get {
                return ResourceManager.GetString("lblCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الجديدة.
        /// </summary>
        public static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور الجديدة.
        /// </summary>
        public static string lblNewPasswordConfirm {
            get {
                return ResourceManager.GetString("lblNewPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغيير كلمة المرور.
        /// </summary>
        public static string lblUpdatePassword {
            get {
                return ResourceManager.GetString("lblUpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب المستخدم يعمل على .
        /// </summary>
        public static string msg1001UserLockedWorking {
            get {
                return ResourceManager.GetString("msg1001UserLockedWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى إسم المستخدم أو كلمة المرور.
        /// </summary>
        public static string msg1002InvalidLogin {
            get {
                return ResourceManager.GetString("msg1002InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إتمام العملية.
        /// </summary>
        public static string msgCannotPerformAction {
            get {
                return ResourceManager.GetString("msgCannotPerformAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم الإرسال.
        /// </summary>
        public static string msgCannotSent {
            get {
                return ResourceManager.GetString("msgCannotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مستخدم بهذا البريد الإلكترونى.
        /// </summary>
        public static string msgEmailNotFound {
            get {
                return ResourceManager.GetString("msgEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ فى إسم المستخدم أو كلمة المرور.
        /// </summary>
        public static string msgLoginInputNotValid {
            get {
                return ResourceManager.GetString("msgLoginInputNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجّل الدخول إلى حسابك في.
        /// </summary>
        public static string msgLogintoProducts1 {
            get {
                return ResourceManager.GetString("msgLogintoProducts1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to للوصول إلى جميع منتجاتنا.
        /// </summary>
        public static string msgLogintoProducts2 {
            get {
                return ResourceManager.GetString("msgLogintoProducts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور.
        /// </summary>
        public static string msgPasswordChange {
            get {
                return ResourceManager.GetString("msgPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور مستخدمة من قبل.
        /// </summary>
        public static string msgPasswordFound {
            get {
                return ResourceManager.GetString("msgPasswordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تكون من.
        /// </summary>
        public static string msgPasswordLenght1 {
            get {
                return ResourceManager.GetString("msgPasswordLenght1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حروف إلى .
        /// </summary>
        public static string msgPasswordLenght2 {
            get {
                return ResourceManager.GetString("msgPasswordLenght2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حروف.
        /// </summary>
        public static string msgPasswordLenght3 {
            get {
                return ResourceManager.GetString("msgPasswordLenght3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        public static string msgPasswordNotMatch {
            get {
                return ResourceManager.GetString("msgPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عند تسجيل الدخول, أنت توافق على إتفاقية الترخيص وقد قرأت بيان الخصوصية.
        /// </summary>
        public static string msgPrivacy {
            get {
                return ResourceManager.GetString("msgPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الإرسال بنجاح.
        /// </summary>
        public static string msgSentSuccessfully {
            get {
                return ResourceManager.GetString("msgSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل عضوية.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرنى.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم يقوم بالعمل على.
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
    }
}
