using appSERP.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace appSERP.appCode.dbCode.INV.Abstract
{
    public interface IdbINVInvoice
    {


        string funINVInvoiceGET(
        int? UserId = null,
        int? phPatId = null,

        int? phInvId = null,
        int? phInvtype = null,
        int? phYEAR = null,
        int? phInvRef = null,
        DateTime? phInvDate = null,
        int? phSellerId = null,
        bool? phPayCash = null,
        bool? phPayCheck = null,
        bool? phPayLater = null,
        float? phInvBaseAmt = null,
        int? phDiscPerc = null,
        bool? phIsPosted = null,
        int? phStoreId = null,
        float? phDiscAmt = null,
        int? phInvSubCost = null,
        string phNotes = null,
        int? phPermitId = null,
        int? phPermitType = null,
        int? phOrderType = null,
        int? phOrderId = null,
        int? phCustomerId = null,
        int? phSaleTax = null,
        int? phSaleTax2 = null,
        int? phPerson = null,
        string phInvSeq = null,
        DateTime? phInvRefDate = null,
        float? phInvCurValue = null,
        int? phInvCur = null,
        float? phInvDisc = null,
        float? phPermitYear = null,
        int? phBankId = null,
        int? phBranchId = null,
        int? phCardNo = null,
        int? phAccountId = null,
        DateTime? phExpireDate = null,
        int? phCardType = null,
        int? phAMT = null,
        float? phCurValue = null,
        float? phBaseAmt = null,
        string phBankSource = null,
        int? phPayVisa = null,
        int? phAreaId = null,
        int? phQutId = null,
        int? phQutType = null,
        int? phTypeId = null,
        bool? phPAYED = null,
        int? phGetComm = null,
        string phDELIVERIES = null,
        float? phReturnOnDelivery = null,
        int? phGoodInvId = null,
        int? phSetSaleRet = null,
        int? phRetOnDelyear = null,
        int? phTableId = null,
        int? phVisitNo = null,
        int? phReqNo = null,
        int? phSurgId = null,
        int? phDebitType = null,
        int? phInsurTrans = null,
        int? phContNo = null,
        int? phInsurancePerc = null,
        int? phCmpAccId = null,
        int? phSalesId = null,
        int? phFromBranches = null,
        bool? phInvIsWait = null,
        bool? phInvIsCancel = null,
        int? phPeriodId = null,
        int? phBranchCompId = null,
        int? phBranchTransId = null,
        int? phCompanyId = null,
        bool? phInvoiceIsActive = null,
        bool? phIsDeleted = null,
        int? pCreatedBy = null,
        DateTime? pCreatedOn = null,
        int? pLastUpdatedBy = null,
        DateTime? pLastUpdatedOn = null,
        int? pdInvDTLId = null,
        int? pdInvId = null,
        int? pdInvType = null,
        int? pdYEAR = null,
        int? pdStoreId = null,
        int? pdItemId = null,
        int? pdUnitId = null,
        DateTime? pdExpireDate = null,
        int? pdBackType = null,
        int? pdBackId = null,
        int? pdBackYear = null,
        int? pdItemPrice = null,
        float? pdItemQty = null,
        DateTime? pdGuaranteeDate = null,
        float? pdTotalItemCredit = null,
        float? pdTotalItemDebit = null,
        float? pdTotalBaseItemCredit = null,
        float? pdTotalBaseItemDebit = null,
        int? pdDiscType = null,
        int? pdDiscValue = null,
        float? pdDiscAmtCredit = null,
        float? pdDiscAmtDebit = null,
        float? pdDiscBaseCredit = null,
        float? pdDiscBaseDebit = null,
        bool? pdIsPosted = null,
        string pdNotes = null,
        string pdAccountId = null,
        float? pdItemCostDebit = null,
        float? pdItemCostCredit = null,
        int? pdSellAccId = null,
        int? pdCostAccId = null,
        int? pdDiscAccId = null,
        int? pdTaxAccId = null,
        float? pdTaxDebit = null,
        float? pdTaxBaseDebit = null,
        float? pdItemCost = null,
        float? pdTaxBaseCredit = null,
        float? pdTaxCredit = null,
        int? pdBackSellAccId = null,
        int? pdBackBuyAccId = null,
        float? pdItemStoreCurValue = null,
        float? pdItemCurVALUE = null,
        float? pdItemCur = null,
        float? pdTotalItemSbaseCredit = null,
        float? pdTotalItemSbaseDebit = null,
        int? pdItemDefCur = null,
        int? pdTransSeq = null,
        int? pdEmpAccId = null,
        float? pdEmpAmt = null,
        float? pdEmpBaseAmt = null,
        int? pdEmpRatio = null,
        float? pdEmpCurValue = null,
        float? pdItemCostBase = null,
        int? pdDelivId = null,
        int? pdDelYear = null,
        int? pdDelTransSeq = null,
        int? pdInStoreId = null,
        string pdNonDescribe = null,
        DateTime? pdDate = null,
        string pdItemName = null,
        float? pdVatAMT = null,
        int? pdVatDebitAccId = null,
        int? pdVatCreditAccId = null,
        int? pdCompanyId = null,
        bool? pdInvIsActive = null,
        bool? pdIsDeleted = null,
        int? pInvLaterId = null,
        int? pInvType = null,
        int? pLInvId = null,
        int? pYEAR = null,
        int? pAccountId = null,
        float? pLaterAmtCredit = null,
        float? pLaterAmtDebit = null,
        float? pLaterCurValue = null,
        float? pLaterBaseAmtCredit = null,
        float? pLaterBaseAmtDebit = null,
        bool? pIsPosted = null,
        string pNotes = null,
        int? pStoreId = null,
        int? pCostCenterId = null,
        int? pTransSeq = null,
        bool? pIsDeleted = null,
        int? pCompanyId = null,
        float? pUsedPoints = null,
        int? pMealPoints = null,
        int? pBranchId = null,
        //POS
        int? pSubSeq = null,
        int? pPayTypeId = null,
        int? pCashDeskId = null,
        int? pInvStatus = null,
        int? pOrderSeq = null,
        float? pInsurance = null,
        int? pInsurPerc = null,
        float? pService = null,
        int? pServicePerc = null,
        float? pTax = null,
        int? pTaxPerc = null,
        float? pDiscount = null,
        int? pDiscountPerc = null,
        int? pPointId = null,
        int? pDelivery = null,
        int? pDeliveryPerc = null,
        string pInvMachine = null,
        string pPcIdentification = null,
        int? pOrderLocSeq = null,
        int? pOrederDaySeq = null,
        int? pInvPayType = null,
        bool? pDeliveryInvoice = null,
        DateTime? pDeliveryDate = null,
        int? pDelLocSeq = null,
        string pInvPhoneNo = null,
        bool? pIsPrepare = null,
        bool? pIsTransPost = null,
        int? pPriceCat = null,
        int? pSiteId = null,
        string pLocAddressInvoice = null,
        int? pAnotherInvId = null,
        int? pCasherDiscount = null,
        int? pDiscountSell = null,
        string pCustomerName = null,
        decimal? pAddAMT = null,
        bool? pDelSheepRemain = null,
        decimal? pDiscAmt = null,
        int? pItemUnitId = null,
        decimal? pPrice = null,
        int? pQty = null,
        float? pQtyPlate = null,
        float? QtyTransfer = null,
        float? QtyLastRemain = null,
        int? pSheepRemainder = null,
        int? pTag = null,
        int? pVatPrice = null,
        float? pVatTotal = null,
        int? pItemType = null,
        // Search Parameters
        string phNumbers = null,
        string psGLVoucherNo = null,
        DateTime? psDateFrom = null,
        DateTime? psDateTo = null,
        int? ppType = null,
        int? pLanguageId = null,
        int? pQueryTypeId = null,
        string pSearchDateFrom = null,
        string pSearchDateTo = null,
        string pInvItemNameL1 = null,
        string pLstUnit = null,
        string pLstInvItemId = null,
        int ? branchId=null
        );
        DataTable GetItemHasInvoice(int? pItemId, int? pUnitId = null);
        object CancelInvoice(int? phINVId, int? pLastUpdatedBy, int? pQueryTypeId);
        DataTable TableManagmentGet(int? pQueryTypeId = null);
        DataTable funGetInvoicePaymentOrderReport(int? pInvId = null, bool? pIsActive = null, int? InvType = null);
        DataTable funGetInvoiceDamageProductReport(int? pInvId = null);
        DataTable funGetInvoiceBuyReport(int? pInvId = null, bool? pIsActive = null);
        DataTable DtINVInvoiceGET(
        int? phInvId = null,
        int? phInvtype = null,
        int? phYEAR = null,
        int? phInvRef = null,
        DateTime? phInvDate = null,
        int? phSellerId = null,
        bool? phPayCash = null,
        bool? phPayCheck = null,
        bool? phPayLater = null,
        float? phInvBaseAmt = null,
        int? phDiscPerc = null,
        bool? phIsPosted = null,
        int? phStoreId = null,
        float? phDiscAmt = null,
        int? phInvSubCost = null,
        string phNotes = null,
        int? phPermitId = null,
        int? phPermitType = null,
        int? phOrderType = null,
        int? phOrderId = null,
        int? phCustomerId = null,
        int? phSaleTax = null,
        int? phSaleTax2 = null,
        int? phPerson = null,
        string phInvSeq = null,
        DateTime? phInvRefDate = null,
        float? phInvCurValue = null,
        int? phInvCur = null,
        float? phInvDisc = null,
        float? phPermitYear = null,
        int? phBankId = null,
        int? phBranchId = null,
        int? phCardNo = null,
        int? phAccountId = null,
        DateTime? phExpireDate = null,
        int? phCardType = null,
        int? phAMT = null,
        float? phCurValue = null,
        float? phBaseAmt = null,
        string phBankSource = null,
        int? phPayVisa = null,
        int? phAreaId = null,
        int? phQutId = null,
        int? phQutType = null,
        int? phTypeId = null,
        bool? phPAYED = null,
        int? phGetComm = null,
        string phDELIVERIES = null,
        float? phReturnOnDelivery = null,
        int? phGoodInvId = null,
        int? phSetSaleRet = null,
        int? phRetOnDelyear = null,
        int? phTableId = null,
        int? phVisitNo = null,
        int? phReqNo = null,
        int? phSurgId = null,
        int? phDebitType = null,
        int? phInsurTrans = null,
        int? phContNo = null,
        int? phInsurancePerc = null,
        int? phCmpAccId = null,
        int? phSalesId = null,
        int? phFromBranches = null,
        bool? phInvIsWait = null,
        bool? phInvIsCancel = null,
        int? phPeriodId = null,
        int? phBranchCompId = null,
        int? phBranchTransId = null,
        int? phCompanyId = null,
        bool? phInvoiceIsActive = null,
        bool? phIsDeleted = null,
        int? pCreatedBy = null,
        DateTime? pCreatedOn = null,
        int? pLastUpdatedBy = null,
        DateTime? pLastUpdatedOn = null,
        int? pdInvDTLId = null,
        int? pdInvId = null,
        int? pdInvType = null,
        int? pdYEAR = null,
        int? pdStoreId = null,
        int? pdItemId = null,
        int? pdUnitId = null,
        DateTime? pdExpireDate = null,
        int? pdBackType = null,
        int? pdBackId = null,
        int? pdBackYear = null,
        int? pdItemPrice = null,
        int? pdItemQty = null,
        DateTime? pdGuaranteeDate = null,
        float? pdTotalItemCredit = null,
        float? pdTotalItemDebit = null,
        float? pdTotalBaseItemCredit = null,
        float? pdTotalBaseItemDebit = null,
        int? pdDiscType = null,
        int? pdDiscValue = null,
        float? pdDiscAmtCredit = null,
        float? pdDiscAmtDebit = null,
        float? pdDiscBaseCredit = null,
        float? pdDiscBaseDebit = null,
        bool? pdIsPosted = null,
        string pdNotes = null,
        string pdAccountId = null,
        float? pdItemCostDebit = null,
        float? pdItemCostCredit = null,
        int? pdSellAccId = null,
        int? pdCostAccId = null,
        int? pdDiscAccId = null,
        int? pdTaxAccId = null,
        float? pdTaxDebit = null,
        float? pdTaxBaseDebit = null,
        float? pdItemCost = null,
        float? pdTaxBaseCredit = null,
        float? pdTaxCredit = null,
        int? pdBackSellAccId = null,
        int? pdBackBuyAccId = null,
        float? pdItemStoreCurValue = null,
        float? pdItemCurVALUE = null,
        float? pdItemCur = null,
        float? pdTotalItemSbaseCredit = null,
        float? pdTotalItemSbaseDebit = null,
        int? pdItemDefCur = null,
        int? pdTransSeq = null,
        int? pdEmpAccId = null,
        float? pdEmpAmt = null,
        float? pdEmpBaseAmt = null,
        int? pdEmpRatio = null,
        float? pdEmpCurValue = null,
        float? pdItemCostBase = null,
        int? pdDelivId = null,
        int? pdDelYear = null,
        int? pdDelTransSeq = null,
        int? pdInStoreId = null,
        string pdNonDescribe = null,
        DateTime? pdDate = null,
        string pdItemName = null,
        float? pdVatAMT = null,
        int? pdVatDebitAccId = null,
        int? pdVatCreditAccId = null,
        int? pdCompanyId = null,
        bool? pdInvIsActive = null,
        bool? pdIsDeleted = null,
        int? pInvLaterId = null,
        int? pInvType = null,
        int? pLInvId = null,
        int? pYEAR = null,
        int? pAccountId = null,
        float? pLaterAmtCredit = null,
        float? pLaterAmtDebit = null,
        float? pLaterCurValue = null,
        float? pLaterBaseAmtCredit = null,
        float? pLaterBaseAmtDebit = null,
        bool? pIsPosted = null,
        string pNotes = null,
        int? pStoreId = null,
        int? pCostCenterId = null,
        int? pTransSeq = null,
        bool? pIsDeleted = null,
        int? pCompanyId = null,
        float? pUsedPoints = null,
        int? pMealPoints = null,
        int? pBranchId = null,
        //POS
        int? pSubSeq = null,
        int? pPayTypeId = null,
        int? pCashDeskId = null,
        int? pInvStatus = null,
        int? pOrderSeq = null,
        float? pInsurance = null,
        int? pInsurPerc = null,
        float? pService = null,
        int? pServicePerc = null,
        float? pTax = null,
        int? pTaxPerc = null,
        float? pDiscount = null,
        int? pDiscountPerc = null,
        int? pPointId = null,
        int? pDelivery = null,
        int? pDeliveryPerc = null,
        string pInvMachine = null,
        string pPcIdentification = null,
        int? pOrderLocSeq = null,
        int? pOrederDaySeq = null,
        int? pInvPayType = null,
        bool? pDeliveryInvoice = null,
        DateTime? pDeliveryDate = null,
        int? pDelLocSeq = null,
        string pInvPhoneNo = null,
        bool? pIsPrepare = null,
        bool? pIsTransPost = null,
        int? pPriceCat = null,
        int? pSiteId = null,
        string pLocAddressInvoice = null,
        int? pAnotherInvId = null,
        int? pCasherDiscount = null,
        int? pDiscountSell = null,
        string pCustomerName = null,
        decimal? pAddAMT = null,
        bool? pDelSheepRemain = null,
        decimal? pDiscAmt = null,
        int? pItemUnitId = null,
        decimal? pPrice = null,
        int? pQty = null,
        int? pQtyPlate = null,
        int? pSheepRemainder = null,
        int? pTag = null,
        int? pVatPrice = null,
        float? pVatTotal = null,
        int? pItemType = null,
        // Search Parameters
        string phNumbers = null,
        string psGLVoucherNo = null,
        DateTime? psDateFrom = null,
        DateTime? psDateTo = null,
        int? ppType = null,
        int? pLanguageId = null,
        int? pQueryTypeId = null,
        string pSearchDateFrom = null,
        string pSearchDateTo = null,
        string pInvItemNameL1 = null,
        string pLstUnit = null,
        string pLstInvItemId = null
        );

        object spInvoiceDtlInsertBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId, int? UserId = null, int? BranchId = null);

        Object spInvoicePOSBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId,
            int? Invtype = null, bool? InvIsWait = null, string CardNo = null, DateTime? InvDate = null, int? PayTypeId = null, string Notes = null, int? CashDeskId = null, float? Insurance = null, int? Service = null, float? Tax = null, float? Discount = null, string InvMachine = null, bool? DeliveryInvoice = null, int? Delivery = null, DateTime? DeliveryDate = null, string InvPhoneNo = null, int? SiteId = null, string LocAddressInvoice = null, float? InvCurValue = null, string CustomerName = null, int? CustomerId = null, int? OrderType = null, int? UsedPoints = null, int? MealPoints = null, string CustomerAddress = null, string CustomerPhoneNumber = null,
            int? UserId = null, int? BranchId = null, int? TableId = null, int? InvStatus = null);

        object spMovementBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId,
             int? InvStatus, int? CashDeskId, DateTime? InvDate = null, string InvPhoneNo = null, string CustomerName = null, float? InvCurValue = null, int? Delivery = null, float? Tax = null, string InvMachine = null, bool? DeliveryInvoice = null, string LocAddressInvoice = null, int? CustomerId = null, int? OrderId = null, int? UserId = null, int? BranchId = null, float? Discount = null, string Notes = null);

        object spReturnBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId,
          int? InvRef = null, int? UserId = null,int?BranchId=null);

        object spInsuranceReturnBulk(ICollection<InvoiceDtl> InvoiceDtls, int CashDeskId, string Numbers,int BranchId);

        object spItemBulk(ICollection<ItemUnit> ItemUnit, int ItemId);

        object spPaymentOrderInsertBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId);

        int getUserId();

        object spPaymentReciverInsertBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId, int? InvType, int? CustomerId, int? StoreId, DateTime? InvDate, string Notes, int? InvRef, DateTime? InvRefDate, bool? InvIsCancel, bool? IsDeleted, int? UserId, int? BranchId, bool? PayCash = null, bool? PayCheck = null, bool? PayLater = null);

        object spMealBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId, int? InvType, int? CustomerId, int? StoreId, DateTime? InvDate, string Notes, int? InvRef, DateTime? InvRefDate, bool? InvIsCancel, bool? IsDeleted, int? UserId = null, int? BranchId = null);

        object spPaymentInsertBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId, int? InvType, int? CustomerId, int? StoreId, DateTime? InvDate, string Notes, int? InvRef, DateTime? InvRefDate, bool? InvIsCancel, bool? IsDeleted, int? UserId, int? BranchId, bool? PayCash = null, bool? PayCheck = null, bool? PayLater = null);

        object spProductionTransInsertBulk(ICollection<InvoiceDtl> InvoiceDtls, int? InvId, int? ProductionId, int? UserId, int? BranchId);

        DataTable POSData(string InvCode, DateTime? DateFrom = null, DateTime? DateTo = null, int? BranchId = null);
        object spReturnData(string psGLVoucherNo,DateTime? psDateFrom = null, DateTime? psDateTo = null);
        int FirstCount { get; set; }
        int SecondCount { get; set; }
        DataTable InvoicePosData { get; set; }
        DataTable TableData { get; set; }

        // BH
        object funInvoiceOrderOrPOS(int? pInvId = null, int? pOrderId = null, int pQueryTypeId = 400
            , string pZatcaResponse = null, bool? pIsPassed = true, DateTime? pDateFrom = null, DateTime? pDateTo = null, int? pBranchId = null, string pInvCode = null);
    }
}
